# Generated by Django 5.1.1 on 2024-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('price', models.IntegerField(max_length=15)),
                ('description', models.TextField()),
                ('chara', models.TextField(max_length=255)),
                ('game', models.TextField(max_length=255)),
                ('category', models.TextField(max_length=255)),
                ('image', models.TextField(max_length=255)),
            ],
        ),
    ]
