# Generated by Django 5.1.1 on 2024-09-18 03:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=1)),
                ('chara', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.TextField(max_length=255)),
            ],
        ),
    ]
